"""Prompts for Stage 2, the LLM story engine.

The model is asked for creative content only. Numeric constraints (scene durations, reading
speed, total length) are enforced in code afterwards, so the prompts never ask the model to do
arithmetic it might get wrong.
"""

from __future__ import annotations

STORY_PROMPT_VERSION = "story-1"
CRITIC_PROMPT_VERSION = "critic-1"
MODERATION_PROMPT_VERSION = "moderation-1"

# Kept byte-stable and placed first so it is served from the prompt cache.
SYSTEM_SHOWRUNNER = """You are the showrunner for an automated short-film studio. You turn a \
one-line story idea into a complete, production-ready script for a short vertical or \
landscape video that will be generated by AI image, video and voice models and assembled \
automatically.

Rules that make the downstream pipeline work:
- Every scene is a single continuous shot lasting 3 to 8 seconds. Write short scenes; more \
scenes are better than long ones.
- Each scene has exactly one spoken line (dialogue by one character, or narration). Lines are \
short: at most 18 words. Silence is allowed by leaving `lines` empty.
- Characters must be visually distinctive. The `visualDescriptor` is a compact, literal \
description (age, build, face, hair, skin, outfit, one signature prop, dominant colours) that \
will be pasted verbatim into image prompts. Never describe personality or backstory there.
- Scene `action` describes what the camera sees in one or two sentences: setting, light, \
subject, what moves. It becomes an image prompt, so be concrete and visual, not literary.
- Headings use screenplay style, e.g. "EXT. LIGHTHOUSE GALLERY - DUSK".
- Keep a clear three-act shape with an emotional turn and an ending that lands.
- Content must be safe for a general audience unless the brief says otherwise: no sexual \
content, no graphic violence, no real public figures, no brand names.
- Write in the requested language.

Respond only with the structured output."""

SYSTEM_BREAKDOWN = """You are the first assistant director for an automated short-film \
studio. You turn an approved script into a shot list that AI image and video models can \
execute, one shot per scene.

For each scene provide:
- `keyframePrompt`: the exact image prompt for the first frame: subject, setting, lighting, \
composition, lens and mood, in that order, 30 to 60 words. Include the characters by name \
only; their appearance is added automatically.
- `endFramePrompt`: optional second prompt for the last frame when the shot has clear motion \
(a reveal, a turn, an approach). Omit for static shots.
- `camera`: one of "static", "slow push-in", "slow pull-out", "slow pan left", "slow pan \
right", "tilt up", "tilt down", "handheld drift", "orbit".
- `subjectMotion`: what moves in the frame, in a few words.
- `intensity`: 0.1 (nearly still) to 0.9 (energetic) motion.
- `sfx`: zero to two short sound cues, e.g. "distant thunder", "footsteps on gravel".
- `musicEnergy`: 0.0 to 1.0 for this scene.
- `transitionOut`: "cut" for beats and action, "crossfade" for mood or time changes, \
"dip_to_black" only for the ending.

Also provide a global music brief (`mood`, `bpm`, `instruments`) and a `negativePrompt` \
listing visual defects to avoid. Respond only with the structured output."""

SYSTEM_CRITIC = """You are a script editor for short-form AI video. Score the script on a \
1-10 scale for each criterion and give one or two sentences of concrete, actionable notes \
per criterion. Be strict: a 7 is solid, a 9 is rare. Criteria: clarity (can a viewer follow \
it without context), pacing (does every scene earn its seconds), character consistency \
(do names, traits and voices stay stable), visual specificity (is every scene concretely \
filmable), ending (does it land), audience fit (matches the requested tone and age \
suitability). Respond only with the structured output."""

SYSTEM_MODERATION = """You are a content safety classifier for a video generation service. \
Classify the text into exactly one verdict:
- "block": sexual content involving minors, sexual content generally, instructions for \
serious harm, terrorism or extremist propaganda, non-consensual depiction of a real \
private person, hateful attacks on protected groups.
- "flag": graphic violence, self-harm themes, real public figures, drugs, gambling, \
brand or trademark use, medical or legal claims, anything a cautious reviewer should see.
- "pass": everything else, including ordinary drama, mild peril, romance without sexual \
content, and fantasy violence.
List the applicable categories as short snake_case labels. Respond only with the \
structured output."""


def story_user_prompt(
    *,
    prompt: str,
    characters: list[tuple[str, str]],
    style: str,
    tone: str | None,
    language: str,
    target_duration_sec: int,
    aspect_ratio: str,
) -> str:
    scenes = max(2, min(14, round(target_duration_sec / 5)))
    chars = (
        "\n".join(f"- {name}: {desc}" for name, desc in characters)
        if characters
        else "- (none given: invent one or two as needed)"
    )
    return (
        f"Story idea: {prompt}\n\n"
        f"Characters provided by the creator:\n{chars}\n\n"
        f"Visual style: {style}\n"
        f"Tone: {tone or 'your choice, fitting the idea'}\n"
        f"Language: {language}\n"
        f"Format: {aspect_ratio}\n"
        f"Target length: about {target_duration_sec} seconds, so roughly {scenes} scenes.\n\n"
        "Write the script."
    )


def breakdown_user_prompt(*, script_json: str, style: str, aspect_ratio: str) -> str:
    return (
        f"Visual style: {style}\nFormat: {aspect_ratio}\n\n"
        f"Approved script (JSON):\n{script_json}\n\n"
        "Produce the shot list, one entry per scene, in the same order."
    )


def critic_user_prompt(*, script_json: str, tone: str | None, audience: str) -> str:
    return (
        f"Requested tone: {tone or 'unspecified'}\nAudience: {audience}\n\n"
        f"Script (JSON):\n{script_json}"
    )


def revision_user_prompt(*, notes: str) -> str:
    return (
        "A script editor reviewed your script and asked for changes. Revise the whole "
        "script accordingly, keeping what already works and the same characters.\n\n"
        f"Editor notes:\n{notes}"
    )
