#!/usr/bin/env node
/**
 * Generates TypeScript types (src/generated/types.ts) and Pydantic models
 * (workers/avg_workers/contracts/models.py) from schemas/*.schema.json.
 *
 *   node scripts/gen.mjs          # write outputs
 *   node scripts/gen.mjs --check  # fail if committed outputs are stale
 */
import { compile } from 'json-schema-to-typescript';
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const repoRoot = resolve(root, '..', '..');
const schemasDir = join(root, 'schemas');
const tsOut = join(root, 'src', 'generated', 'types.ts');
const pyOut = join(repoRoot, 'workers', 'avg_workers', 'contracts', 'generated', '__init__.py');
const check = process.argv.includes('--check');

const HEADER = '/* eslint-disable */\n// AUTO-GENERATED by packages/contracts/scripts/gen.mjs — do not edit.\n\n';

async function generateTs() {
  const files = (await readdir(schemasDir)).filter((f) => f.endsWith('.schema.json')).sort();
  let out = HEADER;
  for (const file of files) {
    const schema = JSON.parse(await readFile(join(schemasDir, file), 'utf8'));
    const ts = await compile(schema, schema.title, {
      bannerComment: '',
      additionalProperties: false,
      strictIndexSignatures: true,
      style: { singleQuote: true, semi: true, printWidth: 100 },
    });
    out += `// ---- ${file} ----\n${ts}\n`;
  }
  return out;
}

function generatePy(target) {
  const workers = join(repoRoot, 'workers');
  const res = spawnSync(
    'uv',
    [
      'run',
      '--quiet',
      'datamodel-codegen',
      '--input',
      schemasDir,
      '--input-file-type',
      'jsonschema',
      '--output',
      target,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.11',
      '--use-schema-description',
      '--use-title-as-name',
      '--field-constraints',
      '--use-double-quotes',
      '--disable-timestamp',
      '--collapse-root-models',
    ],
    { cwd: workers, stdio: 'inherit' },
  );
  if (res.status !== 0) {
    throw new Error(`datamodel-codegen failed with status ${res.status}`);
  }
}

async function readIfExists(p) {
  return existsSync(p) ? readFile(p, 'utf8') : null;
}

async function main() {
  const ts = await generateTs();
  if (check) {
    const current = await readIfExists(tsOut);
    if (current !== ts) {
      console.error(`Stale: ${tsOut}. Run "pnpm gen:contracts".`);
      process.exitCode = 1;
    }
  } else {
    await mkdir(dirname(tsOut), { recursive: true });
    await writeFile(tsOut, ts);
    console.log(`wrote ${tsOut}`);
  }

  const pyTarget = check ? join(tmpdir(), `avg-contracts-${process.pid}`) : dirname(pyOut);
  await mkdir(pyTarget, { recursive: true });
  generatePy(pyTarget);
  if (check) {
    const files = (await readdir(pyTarget)).sort();
    for (const f of files) {
      const fresh = await readFile(join(pyTarget, f), 'utf8');
      const current = await readIfExists(join(dirname(pyOut), f));
      if (current !== fresh) {
        console.error(`Stale: ${join(dirname(pyOut), f)}. Run "pnpm gen:contracts".`);
        process.exitCode = 1;
      }
    }
  } else {
    console.log(`wrote ${dirname(pyOut)}/`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
