{{- if and .Values.migrations.enabled .Values.api.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "avg.fullname" . }}-migrate
  labels:
    {{- include "avg.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrations.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "avg.selectorLabels" (dict "root" . "component" "migrate") | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "avg.apiServiceAccount" . }}
      {{- include "avg.imagePullSecrets" . | nindent 6 }}
      securityContext:
        fsGroup: 10001
      containers:
        - name: migrate
          image: {{ include "avg.image" (dict "root" . "image" .Values.api.image) }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["node", "node_modules/prisma/build/index.js", "migrate", "deploy"]
          {{- include "avg.envFrom" . | nindent 10 }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          securityContext:
            {{- include "avg.securityContext" . | nindent 12 }}
{{- end }}
