import type { Metadata } from 'next';
import Link from 'next/link';
import { LEGAL } from '@/lib/legal';

export const metadata: Metadata = { title: `Terms of Service — ${LEGAL.product}` };

export default function TermsPage() {
  const { company, product } = LEGAL;
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="meta">Effective {LEGAL.effectiveDate}</p>
      <p>
        These terms govern your use of {product}, an AI video generation service operated by{' '}
        {company} (&ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or using the service
        you agree to them. If you use the service on behalf of an organisation, you represent that
        you can bind it to these terms.
      </p>

      <h2>1. The service</h2>
      <p>
        {product} turns a written story idea and optional character descriptions into a produced
        video: a script, character and scene images, animated clips, voice, music, sound effects and
        subtitles, assembled into a downloadable MP4. Generation is performed by machine-learning
        models, some of which are provided by third parties listed on our{' '}
        <Link href="/legal/subprocessors">sub-processors page</Link>. Output is probabilistic:
        results vary between runs and may contain errors, artefacts or content you did not intend.
        We flag known quality issues on the job page and let you regenerate.
      </p>

      <h2>2. Accounts and eligibility</h2>
      <p>
        You must be at least 18 years old. You are responsible for activity under your account and
        for keeping your sign-in credentials secure. One person may not maintain more than one free
        workspace.
      </p>

      <h2>3. Plans, credits and payment</h2>
      <ul>
        <li>
          Paid plans are billed in advance, monthly or yearly, through Stripe. Each plan grants a
          credit allowance per billing period. Credits are held when a video starts, charged for
          what is actually produced, and returned if a video fails before producing a deliverable.
        </li>
        <li>
          Unused plan credits roll over as described on the pricing page and then expire. Purchased
          credit packs do not expire while your account is active.
        </li>
        <li>
          Credits have no cash value and are not transferable. Except where the law requires
          otherwise, payments are non-refundable; we will, at our discretion, refund charges caused
          by a fault on our side.
        </li>
        <li>
          We may change prices with at least 30 days&rsquo; notice. Changes apply from your next
          billing period.
        </li>
      </ul>

      <h2>4. Your content</h2>
      <p>
        You keep ownership of the story ideas, character descriptions and other material you submit
        (&ldquo;inputs&rdquo;). Subject to these terms and to the extent permitted by law, you own
        the videos and other material the service generates for you (&ldquo;outputs&rdquo;) and may
        use them commercially. You grant us a licence to store, process, reproduce and transmit
        inputs and outputs as needed to provide the service, to prevent abuse, and to improve
        reliability using aggregated, de-identified statistics. We do not use your inputs or outputs
        to train generative models without your explicit opt-in.
      </p>
      <p>
        Because outputs are generated by AI, similar outputs may be produced for other users, and we
        cannot guarantee that outputs are unique or that they do not resemble existing works.
        Copyright treatment of AI-generated material differs between countries; obtain your own
        advice before relying on exclusivity.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You may not use the service to create or distribute content that:</p>
      <ul>
        <li>is sexual or exploitative involving minors, or sexualises anyone without consent;</li>
        <li>
          depicts a real person in a way that is deceptive, defamatory or harassing, including
          synthetic likenesses or voices of real people without their documented consent;
        </li>
        <li>promotes violence, terrorism, self-harm or hatred against protected groups;</li>
        <li>infringes intellectual-property, privacy or publicity rights of others;</li>
        <li>is intended to deceive (fraud, disinformation, impersonation of organisations);</li>
        <li>violates any applicable law or the usage policies of our model providers.</li>
      </ul>
      <p>
        You must not probe or disrupt the service, resell it without a written agreement, or
        automate access beyond the published API and your plan&rsquo;s rate limits. Automated
        moderation screens inputs and outputs; flagged jobs may be blocked, held for review or
        removed, and repeated violations lead to suspension without refund.
      </p>

      <h2>6. AI disclosure</h2>
      <p>
        Outputs are synthetic media. Where a platform, law or audience expects it, you are
        responsible for disclosing that a video was AI-generated. We may embed provenance metadata
        or an invisible watermark in outputs.
      </p>

      <h2>7. Availability and changes</h2>
      <p>
        We aim for high availability but do not guarantee uninterrupted service. Third-party model
        providers can change or withdraw models; we route around outages where possible and may
        substitute equivalent models. We may modify or discontinue features with reasonable notice.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can delete your account at any time from the account page; deletion becomes irreversible
        after a {LEGAL.deletionGraceDays}-day grace period. We may suspend or terminate accounts
        that breach these terms, with notice where practical. Sections 4, 9, 10 and 11 survive
        termination.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        The service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;. To the fullest
        extent permitted by law we disclaim all warranties, express or implied, including fitness
        for a particular purpose, non-infringement and accuracy of outputs.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        To the extent permitted by law, we are not liable for indirect, incidental, special or
        consequential damages, or for loss of profits, data or goodwill, arising from the service.
        Our total liability for any claim is limited to the amount you paid us in the twelve months
        before the claim arose. Nothing in these terms limits liability that cannot be limited by
        law.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These terms are governed by the laws of {LEGAL.jurisdiction}, and disputes are subject to
        the exclusive jurisdiction of its courts, without prejudice to mandatory consumer
        protections in your country of residence.
      </p>

      <h2>12. Changes to these terms</h2>
      <p>
        We may update these terms. Material changes are announced by email or in the dashboard at
        least 14 days before they take effect. Continued use after that date is acceptance.
      </p>

      <h2>13. Contact</h2>
      <p>
        {company}, {LEGAL.address}. Legal notices:{' '}
        <a href={`mailto:${LEGAL.legalEmail}`}>{LEGAL.legalEmail}</a>. Support:{' '}
        <a href={`mailto:${LEGAL.supportEmail}`}>{LEGAL.supportEmail}</a>.
      </p>
    </>
  );
}
